-- Lakbay Baguio anonymous nearby chat
-- Run this entire file in the Supabase SQL editor, then enable Anonymous Sign-Ins.
-- Exact coordinates are stored only in the protected presence table. The public
-- API returns distance bands plus coordinates rounded to a coarse map cell.

begin;

create extension if not exists pgcrypto;
create schema if not exists extensions;
create extension if not exists postgis with schema extensions;

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  alias text not null check (
    alias ~ '^(Cloud|Cozy|Foggy|Gentle|Misty|Pine|Quiet|Sage|Sunny|Wandering)(Deer|Finch|Fox|Hiker|Owl|Panda|Robin|Spruce|Taho|Trail)[0-9]{2}$'
  ),
  avatar_seed integer not null default 0 check (avatar_seed between 0 and 7),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

update public.profiles
set avatar_seed = ((avatar_seed % 8) + 8) % 8
where avatar_seed not between 0 and 7;

do $$
begin
  if not exists (
    select 1
    from pg_catalog.pg_constraint
    where conrelid = 'public.profiles'::regclass
      and conname = 'profiles_avatar_seed_check'
  ) then
    alter table public.profiles
      add constraint profiles_avatar_seed_check check (avatar_seed between 0 and 7);
  end if;
end $$;

create table if not exists public.presence (
  user_id uuid primary key references public.profiles(user_id) on delete cascade,
  location extensions.geography(point, 4326) not null,
  is_discoverable boolean not null default false,
  last_seen timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '90 seconds')
);

alter table public.presence add column if not exists expires_at timestamptz;
update public.presence
set expires_at = now() + interval '90 seconds'
where expires_at is null;
alter table public.presence
  alter column expires_at set default (now() + interval '90 seconds'),
  alter column expires_at set not null;

create index if not exists presence_location_gix on public.presence using gist (location);
create index if not exists presence_active_idx on public.presence (last_seen desc) where is_discoverable;
create index if not exists presence_expiry_idx on public.presence (is_discoverable, expires_at);

create table if not exists public.chat_requests (
  id uuid primary key default gen_random_uuid(),
  sender_id uuid not null references public.profiles(user_id) on delete cascade,
  receiver_id uuid not null references public.profiles(user_id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'declined')),
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '24 hours'),
  responded_at timestamptz,
  check (sender_id <> receiver_id)
);

alter table public.chat_requests add column if not exists expires_at timestamptz;
update public.chat_requests
set expires_at = created_at + interval '24 hours'
where expires_at is null;
alter table public.chat_requests
  alter column expires_at set default (now() + interval '24 hours'),
  alter column expires_at set not null;

create unique index if not exists one_pending_request_per_pair
  on public.chat_requests (
    least(sender_id::text, receiver_id::text),
    greatest(sender_id::text, receiver_id::text)
  )
  where status = 'pending';

create index if not exists chat_requests_receiver_expiry_idx
  on public.chat_requests (receiver_id, status, expires_at desc);

create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now()
);

create table if not exists public.conversation_members (
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  user_id uuid not null references public.profiles(user_id) on delete cascade,
  joined_at timestamptz not null default now(),
  last_read_at timestamptz not null default now(),
  left_at timestamptz,
  primary key (conversation_id, user_id)
);

alter table public.conversation_members add column if not exists left_at timestamptz;

create index if not exists conversation_members_user_idx on public.conversation_members (user_id, joined_at desc);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  sender_id uuid not null default auth.uid() references public.profiles(user_id) on delete cascade,
  body text not null check (char_length(btrim(body)) between 1 and 600),
  created_at timestamptz not null default now()
);

alter table public.messages alter column id set generated always;

create index if not exists messages_conversation_time_idx on public.messages (conversation_id, created_at);

create table if not exists public.blocks (
  blocker_id uuid not null default auth.uid() references public.profiles(user_id) on delete cascade,
  blocked_id uuid not null references public.profiles(user_id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blocker_id, blocked_id),
  check (blocker_id <> blocked_id)
);

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null default auth.uid() references public.profiles(user_id) on delete cascade,
  reported_id uuid not null references public.profiles(user_id) on delete cascade,
  conversation_id uuid references public.conversations(id) on delete set null,
  reason text not null check (reason in ('harassment', 'spam', 'unsafe', 'other')),
  details text check (details is null or char_length(details) <= 1000),
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  check (reporter_id <> reported_id)
);

alter table public.reports alter column id set generated always;

create table if not exists public.restaurant_inquiries (
  id uuid primary key default gen_random_uuid(),
  restaurant_name text not null check (char_length(restaurant_name) between 2 and 100),
  contact_name text not null check (char_length(contact_name) between 2 and 80),
  email text not null check (char_length(email) between 5 and 160),
  phone text check (phone is null or char_length(phone) <= 30),
  address text not null check (char_length(address) between 5 and 240),
  social_url text check (social_url is null or char_length(social_url) <= 300),
  message text not null check (char_length(message) between 20 and 1200),
  status text not null default 'new' check (status in ('new', 'reviewing', 'contacted', 'declined', 'featured')),
  consented_at timestamptz not null,
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create index if not exists restaurant_inquiries_email_created_idx
  on public.restaurant_inquiries (email, created_at desc);

alter table public.profiles enable row level security;
alter table public.presence enable row level security;
alter table public.chat_requests enable row level security;
alter table public.conversations enable row level security;
alter table public.conversation_members enable row level security;
alter table public.messages enable row level security;
alter table public.blocks enable row level security;
alter table public.reports enable row level security;
alter table public.restaurant_inquiries enable row level security;

create or replace function public.can_access_conversation(p_conversation_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select
    exists (
      select 1
      from public.conversation_members mine
      where mine.conversation_id = p_conversation_id
        and mine.user_id = auth.uid()
        and mine.left_at is null
    )
    and not exists (
      select 1
      from public.conversation_members ended_member
      where ended_member.conversation_id = p_conversation_id
        and ended_member.left_at is not null
    )
    and not exists (
      select 1
      from public.conversation_members other_member
      join public.blocks b
        on (b.blocker_id = auth.uid() and b.blocked_id = other_member.user_id)
        or (b.blocker_id = other_member.user_id and b.blocked_id = auth.uid())
      where other_member.conversation_id = p_conversation_id
        and other_member.user_id <> auth.uid()
    );
$$;

drop policy if exists "Authenticated users can read aliases" on public.profiles;
drop policy if exists "Users read their own profile" on public.profiles;
create policy "Users read their own profile"
  on public.profiles for select to authenticated using (user_id = auth.uid());

drop policy if exists "Users create their own profile" on public.profiles;
create policy "Users create their own profile"
  on public.profiles for insert to authenticated with check (user_id = auth.uid());

drop policy if exists "Users update their own profile" on public.profiles;

drop policy if exists "Participants read their chat requests" on public.chat_requests;
create policy "Participants read their chat requests"
  on public.chat_requests for select to authenticated
  using (sender_id = auth.uid() or receiver_id = auth.uid());

drop policy if exists "Members read conversations" on public.conversations;
create policy "Members read conversations"
  on public.conversations for select to authenticated
  using (public.can_access_conversation(id));

drop policy if exists "Members read conversation membership" on public.conversation_members;
create policy "Members read conversation membership"
  on public.conversation_members for select to authenticated
  using (public.can_access_conversation(conversation_id));

drop policy if exists "Members read messages" on public.messages;
create policy "Members read messages"
  on public.messages for select to authenticated
  using (public.can_access_conversation(conversation_id));

drop policy if exists "Members send their own messages" on public.messages;
create policy "Members send their own messages"
  on public.messages for insert to authenticated
  with check (
    sender_id = auth.uid()
    and public.can_access_conversation(conversation_id)
    and char_length(btrim(body)) between 1 and 600
  );

drop policy if exists "Users read their own blocks" on public.blocks;
create policy "Users read their own blocks"
  on public.blocks for select to authenticated using (blocker_id = auth.uid());

drop policy if exists "Users remove their own blocks" on public.blocks;
create policy "Users remove their own blocks"
  on public.blocks for delete to authenticated using (blocker_id = auth.uid());

drop policy if exists "Users submit their own reports" on public.reports;
create policy "Users submit their own reports"
  on public.reports for insert to authenticated
  with check (
    reporter_id = auth.uid()
    and reported_id <> auth.uid()
    and conversation_id is not null
    and public.can_access_conversation(conversation_id)
    and exists (
      select 1
      from public.conversation_members reported_member
      where reported_member.conversation_id = reports.conversation_id
        and reported_member.user_id = reports.reported_id
        and reported_member.user_id <> auth.uid()
    )
  );

create or replace function public.upsert_presence(
  p_latitude double precision,
  p_longitude double precision,
  p_discoverable boolean default true
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_location public.presence.location%type;
  v_previous_location public.presence.location%type;
  v_previous_seen timestamptz;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(auth.uid()::text, 7100));

  if p_discoverable is not true then
    delete from public.presence where user_id = auth.uid();
    return;
  end if;

  -- A deliberately broad service boundary prevents this Baguio-only feature
  -- from being used as a general-purpose location tracker.
  if p_latitude not between 16.20 and 16.60
    or p_longitude not between 120.40 and 120.80 then
    raise exception 'Nearby is available only around Baguio';
  end if;

  v_location := extensions.st_setsrid(
    extensions.st_makepoint(p_longitude, p_latitude),
    4326
  )::extensions.geography;

  select p.location, p.last_seen
  into v_previous_location, v_previous_seen
  from public.presence p
  where p.user_id = auth.uid()
  for update;

  -- Browser coordinates are not attestable, but rejecting implausible jumps
  -- makes repeated spoofed-origin triangulation harder for one identity.
  if found
    and v_previous_seen > now() - interval '60 seconds'
    and extensions.st_distance(v_previous_location, v_location) > 2000 then
    raise exception 'Location changed too quickly. Please try again shortly';
  end if;

  insert into public.presence (user_id, location, is_discoverable, last_seen, expires_at)
  values (
    auth.uid(),
    v_location,
    true,
    now(),
    now() + interval '90 seconds'
  )
  on conflict (user_id) do update set
    location = excluded.location,
    is_discoverable = true,
    last_seen = now(),
    expires_at = now() + interval '90 seconds';
end;
$$;

create or replace function public.set_presence_offline()
returns void
language sql
security definer
set search_path = ''
as $$
  delete from public.presence where user_id = auth.uid();
$$;

drop function if exists public.nearby_profiles(double precision, double precision, integer);
drop function if exists public.nearby_profiles(integer);

create or replace function public.nearby_profiles(p_radius_meters integer default 5000)
returns table (
  user_id uuid,
  alias text,
  avatar_seed integer,
  distance_band text,
  display_latitude double precision,
  display_longitude double precision,
  last_seen timestamptz
)
language sql
stable
security definer
set search_path = ''
as $$
  with origin as (
    select mine.location as point
    from public.presence mine
    where mine.user_id = auth.uid()
      and mine.is_discoverable
      and mine.expires_at > now()
  ), candidates as (
    select
      p.user_id,
      p.alias,
      p.avatar_seed,
      pr.last_seen,
      pr.location,
      extensions.st_distance(pr.location, origin.point) as distance_meters
    from public.presence pr
    join public.profiles p on p.user_id = pr.user_id
    cross join origin
    where auth.uid() is not null
      and pr.user_id <> auth.uid()
      and pr.is_discoverable
      and pr.expires_at > now()
      -- Keep the argument for the existing browser contract, but never allow a
      -- caller to binary-search distance by varying it.
      and extensions.st_dwithin(pr.location, origin.point, 5000)
      and not exists (
        select 1 from public.blocks b
        where (b.blocker_id = auth.uid() and b.blocked_id = pr.user_id)
           or (b.blocker_id = pr.user_id and b.blocked_id = auth.uid())
      )
  )
  select
    candidates.user_id,
    candidates.alias,
    candidates.avatar_seed,
    case
      when distance_meters < 2000 then 'Within 2 km'
      else '2–5 km'
    end as distance_band,
    (
      round((extensions.st_y(candidates.location::extensions.geometry) / 0.02)::numeric) * 0.02
    )::double precision as display_latitude,
    (
      round((extensions.st_x(candidates.location::extensions.geometry) / 0.02)::numeric) * 0.02
    )::double precision as display_longitude,
    date_trunc('minute', candidates.last_seen) as last_seen
  from candidates
  -- A stable hourly shuffle avoids leaking exact-distance ordering.
  order by md5(candidates.user_id::text || date_trunc('hour', now())::text)
  limit 30;
$$;

create or replace function public.request_chat(p_target_user_id uuid)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_request_id uuid;
begin
  if auth.uid() is null or p_target_user_id = auth.uid() then
    raise exception 'Invalid chat request';
  end if;
  if not exists (
    select 1
    from public.presence mine
    join public.presence target on target.user_id = p_target_user_id
    where mine.user_id = auth.uid()
      and mine.is_discoverable
      and target.is_discoverable
      and mine.expires_at > now()
      and target.expires_at > now()
      and extensions.st_dwithin(mine.location, target.location, 5000)
  ) then
    raise exception 'That traveler is no longer available';
  end if;
  if exists (
    select 1 from public.blocks
    where (blocker_id = auth.uid() and blocked_id = p_target_user_id)
       or (blocker_id = p_target_user_id and blocked_id = auth.uid())
  ) then
    raise exception 'Chat is unavailable';
  end if;
  if (
    select count(*)
    from public.chat_requests
    where sender_id = auth.uid() and created_at > now() - interval '1 hour'
  ) >= 12 then
    raise exception 'Too many chat requests. Please try again later';
  end if;

  update public.chat_requests
  set status = 'declined', responded_at = now()
  where status = 'pending'
    and expires_at <= now()
    and ((sender_id = auth.uid() and receiver_id = p_target_user_id)
      or (sender_id = p_target_user_id and receiver_id = auth.uid()));
  if exists (
    select 1
    from public.conversation_members mine
    join public.conversation_members theirs using (conversation_id)
    where mine.user_id = auth.uid() and theirs.user_id = p_target_user_id
      and mine.left_at is null and theirs.left_at is null
  ) then
    raise exception 'You already have a conversation with this traveler';
  end if;

  select id into v_request_id
  from public.chat_requests
  where status = 'pending'
    and expires_at > now()
    and ((sender_id = auth.uid() and receiver_id = p_target_user_id)
      or (sender_id = p_target_user_id and receiver_id = auth.uid()))
  limit 1;

  if v_request_id is not null then return v_request_id; end if;

  begin
    insert into public.chat_requests (sender_id, receiver_id, expires_at)
    values (auth.uid(), p_target_user_id, now() + interval '24 hours')
    returning id into v_request_id;
  exception when unique_violation then
    select r.id into v_request_id
    from public.chat_requests r
    where r.status = 'pending'
      and r.expires_at > now()
      and ((r.sender_id = auth.uid() and r.receiver_id = p_target_user_id)
        or (r.sender_id = p_target_user_id and r.receiver_id = auth.uid()))
    limit 1;
  end;

  if v_request_id is null then
    raise exception 'Chat request could not be created';
  end if;
  return v_request_id;
end;
$$;

create or replace function public.list_chat_requests()
returns table (
  request_id uuid,
  sender_id uuid,
  sender_alias text,
  avatar_seed integer,
  created_at timestamptz
)
language sql
stable
security definer
set search_path = ''
as $$
  select r.id, r.sender_id, p.alias, p.avatar_seed, r.created_at
  from public.chat_requests r
  join public.profiles p on p.user_id = r.sender_id
  where r.receiver_id = auth.uid()
    and r.status = 'pending'
    and r.expires_at > now()
    and not exists (
      select 1 from public.blocks b
      where (b.blocker_id = auth.uid() and b.blocked_id = r.sender_id)
         or (b.blocker_id = r.sender_id and b.blocked_id = auth.uid())
    )
  order by r.created_at desc;
$$;

create or replace function public.respond_to_chat_request(p_request_id uuid, p_accept boolean)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_request public.chat_requests%rowtype;
  v_conversation_id uuid;
begin
  select * into v_request
  from public.chat_requests
  where id = p_request_id
    and receiver_id = auth.uid()
    and status = 'pending'
    and expires_at > now()
  for update;

  if not found then raise exception 'Chat request is no longer available'; end if;

  if not p_accept then
    update public.chat_requests set status = 'declined', responded_at = now() where id = p_request_id;
    return null;
  end if;

  if exists (
    select 1 from public.blocks
    where (blocker_id = auth.uid() and blocked_id = v_request.sender_id)
       or (blocker_id = v_request.sender_id and blocked_id = auth.uid())
  ) then
    raise exception 'Chat is unavailable';
  end if;

  select mine.conversation_id into v_conversation_id
  from public.conversation_members mine
  join public.conversation_members theirs using (conversation_id)
  where mine.user_id = auth.uid() and theirs.user_id = v_request.sender_id
    and mine.left_at is null and theirs.left_at is null
  limit 1;

  if v_conversation_id is null then
    insert into public.conversations default values returning id into v_conversation_id;
    insert into public.conversation_members (conversation_id, user_id)
    values (v_conversation_id, auth.uid()), (v_conversation_id, v_request.sender_id);
  end if;

  update public.chat_requests set status = 'accepted', responded_at = now() where id = p_request_id;
  return v_conversation_id;
end;
$$;

create or replace function public.list_conversations()
returns table (
  conversation_id uuid,
  partner_id uuid,
  partner_alias text,
  avatar_seed integer,
  distance_band text,
  last_message text,
  last_message_at timestamptz,
  unread_count bigint
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    c.id,
    partner.user_id,
    partner_profile.alias,
    partner_profile.avatar_seed,
    case
      when partner_presence.user_id is null
        or partner_presence.is_discoverable is not true
        or partner_presence.expires_at <= now()
      then 'Offline'
      else 'Active now'
    end,
    last_message.body,
    last_message.created_at,
    (
      select count(*)
      from public.messages unread
      where unread.conversation_id = c.id
        and unread.sender_id <> auth.uid()
        and unread.created_at > mine.last_read_at
    )
  from public.conversation_members mine
  join public.conversations c on c.id = mine.conversation_id
  join public.conversation_members partner
    on partner.conversation_id = c.id and partner.user_id <> auth.uid()
  join public.profiles partner_profile on partner_profile.user_id = partner.user_id
  left join public.presence partner_presence on partner_presence.user_id = partner.user_id
  left join lateral (
    select m.body, m.created_at
    from public.messages m
    where m.conversation_id = c.id
    order by m.created_at desc
    limit 1
  ) last_message on true
  where mine.user_id = auth.uid()
    and public.can_access_conversation(c.id)
    and not exists (
      select 1 from public.blocks b
      where (b.blocker_id = auth.uid() and b.blocked_id = partner.user_id)
         or (b.blocker_id = partner.user_id and b.blocked_id = auth.uid())
    )
  order by coalesce(last_message.created_at, c.created_at) desc;
$$;

create or replace function public.mark_conversation_read(p_conversation_id uuid)
returns void
language sql
security definer
set search_path = ''
as $$
  update public.conversation_members
  set last_read_at = now()
  where conversation_id = p_conversation_id
    and user_id = auth.uid()
    and public.can_access_conversation(p_conversation_id);
$$;

create or replace function public.block_user(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null or p_user_id = auth.uid() then
    raise exception 'Invalid block target';
  end if;

  insert into public.blocks (blocker_id, blocked_id)
  values (auth.uid(), p_user_id)
  on conflict do nothing;

  update public.chat_requests
  set status = 'declined', responded_at = now()
  where status = 'pending'
    and ((sender_id = auth.uid() and receiver_id = p_user_id)
      or (sender_id = p_user_id and receiver_id = auth.uid()));
end;
$$;

create or replace function public.end_conversation(p_conversation_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.can_access_conversation(p_conversation_id) then
    raise exception 'Conversation is unavailable';
  end if;

  -- Conversation members and messages cascade from this delete. Reports retain
  -- their moderation record with a null conversation_id.
  delete from public.conversations where id = p_conversation_id;
end;
$$;

create or replace function public.cleanup_inactive_conversations()
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  deleted_count integer;
begin
  delete from public.conversations c
  where coalesce(
    (select max(m.created_at) from public.messages m where m.conversation_id = c.id),
    c.created_at
  ) <= now() - interval '30 minutes';
  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;

create or replace function public.cleanup_stale_presence()
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  deleted_count integer;
begin
  delete from public.presence where expires_at <= now();
  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;

create or replace function public.enforce_message_rate_limit()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  new.sender_id := auth.uid();
  new.created_at := clock_timestamp();
  new.body := btrim(new.body);

  if not public.can_access_conversation(new.conversation_id) then
    raise exception 'Conversation is unavailable';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(auth.uid()::text, 7101));
  if (
    select count(*)
    from public.messages
    where sender_id = auth.uid()
      and created_at > now() - interval '1 minute'
  ) >= 15 then
    raise exception 'Message rate limit reached. Please wait a moment';
  end if;
  return new;
end;
$$;

drop trigger if exists messages_rate_limit on public.messages;
create trigger messages_rate_limit
  before insert on public.messages
  for each row execute function public.enforce_message_rate_limit();

create or replace function public.enforce_report_integrity()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  new.reporter_id := auth.uid();
  new.created_at := clock_timestamp();
  new.resolved_at := null;

  if new.reported_id = auth.uid()
    or new.conversation_id is null
    or not public.can_access_conversation(new.conversation_id)
    or not exists (
      select 1
      from public.conversation_members reported_member
      where reported_member.conversation_id = new.conversation_id
        and reported_member.user_id = new.reported_id
        and reported_member.user_id <> auth.uid()
    ) then
    raise exception 'Invalid report target';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(auth.uid()::text, 7102));
  if (
    select count(*)
    from public.reports r
    where r.reporter_id = auth.uid()
      and r.created_at > now() - interval '1 day'
  ) >= 5 then
    raise exception 'Report rate limit reached';
  end if;

  return new;
end;
$$;

drop trigger if exists reports_integrity on public.reports;
create trigger reports_integrity
  before insert on public.reports
  for each row execute function public.enforce_report_integrity();

revoke all on public.profiles, public.presence, public.chat_requests, public.conversations,
  public.conversation_members, public.messages, public.blocks, public.reports,
  public.restaurant_inquiries from anon, authenticated;

grant all on public.restaurant_inquiries to service_role;

grant select, insert on public.profiles to authenticated;
grant select on public.chat_requests, public.conversations, public.conversation_members to authenticated;
grant select, insert on public.messages to authenticated;
grant select, delete on public.blocks to authenticated;
grant insert on public.reports to authenticated;
grant usage, select on sequence public.messages_id_seq to authenticated;
grant usage, select on sequence public.reports_id_seq to authenticated;

revoke all on function public.can_access_conversation(uuid) from public, anon, authenticated;
revoke all on function public.upsert_presence(double precision, double precision, boolean) from public, anon, authenticated;
revoke all on function public.set_presence_offline() from public, anon, authenticated;
revoke all on function public.nearby_profiles(integer) from public, anon, authenticated;
revoke all on function public.request_chat(uuid) from public, anon, authenticated;
revoke all on function public.list_chat_requests() from public, anon, authenticated;
revoke all on function public.respond_to_chat_request(uuid, boolean) from public, anon, authenticated;
revoke all on function public.list_conversations() from public, anon, authenticated;
revoke all on function public.mark_conversation_read(uuid) from public, anon, authenticated;
revoke all on function public.block_user(uuid) from public, anon, authenticated;
revoke all on function public.end_conversation(uuid) from public, anon, authenticated;
revoke all on function public.cleanup_inactive_conversations() from public, anon, authenticated;
revoke all on function public.cleanup_stale_presence() from public, anon, authenticated;
revoke all on function public.enforce_message_rate_limit() from public, anon, authenticated;
revoke all on function public.enforce_report_integrity() from public, anon, authenticated;

grant execute on function public.can_access_conversation(uuid) to authenticated;
grant execute on function public.upsert_presence(double precision, double precision, boolean) to authenticated;
grant execute on function public.set_presence_offline() to authenticated;
grant execute on function public.nearby_profiles(integer) to authenticated;
grant execute on function public.request_chat(uuid) to authenticated;
grant execute on function public.list_chat_requests() to authenticated;
grant execute on function public.respond_to_chat_request(uuid, boolean) to authenticated;
grant execute on function public.list_conversations() to authenticated;
grant execute on function public.mark_conversation_read(uuid) to authenticated;
grant execute on function public.block_user(uuid) to authenticated;
grant execute on function public.end_conversation(uuid) to authenticated;

-- Run cleanup_stale_presence from a trusted scheduled job only.
grant execute on function public.cleanup_stale_presence() to service_role;
grant execute on function public.cleanup_inactive_conversations() to service_role;

-- Enable this extension and job from the Supabase SQL editor. The named-job
-- check keeps this source safe to run again during future schema updates.
create extension if not exists pg_cron with schema pg_catalog;
select cron.schedule(
  'cleanup-inactive-lakbay-chats',
  '*/5 * * * *',
  $job$select public.cleanup_inactive_conversations();$job$
)
where not exists (select 1 from cron.job where jobname = 'cleanup-inactive-lakbay-chats');

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
    and not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'messages'
    ) then
    alter publication supabase_realtime add table public.messages;
  end if;
end $$;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
    and not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'chat_requests'
    ) then
    alter publication supabase_realtime add table public.chat_requests;
  end if;
end $$;

commit;
